[package]
name = "add"
version = "0.1.0"
authors = ["Sarah Allen <sarah@ultrasaurus.com>"]
edition = "2018"

# Note: header file generation happens in build.rs
[lib]
name = "add"
crate-type = ["staticlib"]    


[build-dependencies]
cbindgen = "0.12"



[dependencies]


